### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by e-zaline** [irena-flextool/flextool-web-interface#14]
Hi,
It would be nice to be able to export the database from the web interface, so to have more interoperability between Spinetoolbox and the web version.

**Comment by soininen** [comment]
It is possible to import and export databases from the web interface already. Please check the Manage project page:

![image](https://user-images.githubusercontent.com/19147159/223656082-2efb0503-5020-42d8-8190-82b054751428.png)

**Comment by e-zaline** [comment]
Ok, thanks. I had seen that by my first thought was that this would download an empty database, and not the current database. Perhaps to have a similar button for Download than for Upload would be clearer. :)
